version: '3.8'
services:
  mongo:
    container_name: my-app-db
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "27017:27017"
    volumes:
      - F:\\projects\\docker_tut\\data:/data/db

  api:
    container_name: api
    build: ./api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - F:\\projects\\docker_tut\\api:/user/src/app
